global:
  resolve_timeout: 5m

route:
  receiver: discord_webhook
  repeat_interval: 1m
  group_by: ['alertname']

receivers:
  - name: discord_webhook
    webhook_configs:
    - url: 'http://discord-alerts:9094'
