global:
  resolve_timeout: 5m

route:
  receiver: discord_webhook
  # todo_hamza
  repeat_interval: 1m
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m

receivers:
  - name: discord_webhook
    webhook_configs:
    - url: 'http://discord-alerts:9094'
